--- #YAML:1.0
name:                Net-Zemanta
version:             0.1
abstract:            Perl bindings for services provided by Zemanta
license:             ~
author:              
    - Tomaz Solc <tomaz@zemanta.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP:                           5.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
